settings:
  title: 'Status Page'
  url: 'https://status.kvsh.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: minecraft-kvsh-xyz # unique identifier
    name: minecraft.kvsh.xyz
    description: 'Play and Find Others on Map.' # default=empty
    url: 'http://minecraft.kvsh.xyz' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: wgui-kvsh-xyz
    name: wgui.kvsh.xyz
    description: 'Built for connect many things to the Wireguard.'
    url: 'https://wgui.kvsh.xyz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: kvsh-xyz
    name: Homepage
    url: 'https://kvsh.xyz'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: qbit2-kvsh-xyz
    name: The Q 2 UI
    url: 'https://qbit2.kvsh.xyz/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: qbit1-kvsh-xyz
    name: The Q 1 UI
    url: 'https://qbit1.kvsh.xyz/'
    method: GET
    expectStatus: 200
    linkable: false
    followRedirect: false # should fetch follow redirects, default=false
